# Setup
title: 王同兴的博客
description: 记录生活、研究技术、分享感悟
url: https://wangtx.github.io
avatar: /avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: Uncle_Xing
  card: summary
logo: logo.png
social:
  name: Songzi Vong
  links:
    - https://twitter.com/Uncle_Xing
    - https://github.com/wangtx
google_site_verification: google735cb6eb196570d8.html
lang: en

sass:
  sass_dir: _sass
  style: :compressed

github:
  username: wangtx
gitalk:
  repo: wangtx.github.io
  client_id: 85520dbd0bfbdff8f64d
  client_secret: cc1481b23040d48a2ac8f603026de393e62ddd7e

# Options

# Replace this value and uncomment to enable Google Analytics tracking
google_analytics: G-W4EGF6DC40

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Tongxing Wang
  url: https://github.com/wangtx/
  email: wangtongxing1991@gmail.com
